---
title: "R Notebook"
output: html_notebook
---


#This is title

## This is a subtitle

```{r}
print('Hello world')
```

# working with CSVs

```{r}
data <- read.csv('../DATA/gapminder.csv')
head(data)
```

In a new chunk, try using the following:
```{r}
dim(data)
```

```{r}
nrow(data)
```

```{r}
ncol(data)
```

```{r}
head(data)
```

```{r}
head(data)
```

```{r}
tail(data)
```

```{r}
colnames(data)
```

```{r}
str(data)
```

```{r}
summary(data)
```
```{r}
test <- data$life_expectancy
head(test)
```

```{r}
# Turing cols into factors

data$country <- as.factor(data$country)
data$region <- as.factor(data$region)

```

```{r}
# HINT [ROWS:COLS]

data.[c("year", "country", "population")]

#Filtering for the country Argentina
data[data$country == "Argentina", ]

```


```{r}
# Adding new cols
data$popmil <- data$population  / 1000000
head(data)
```


```{r}
```


```{r}
```


```{r}
```






